version: '3.6'

services:
  rocklov-db:
    image: mongo:4.1
    container_name: rocklov-db
    ports:
      - '27017:27017'
    networks:
      - rocklov-network

  rocklov-api:
    image: qaninja/rocklov-api:v3
    container_name: rocklov-api
    environment:
      - NODE_ENV=development
    ports:
      - '3333:3333'
    networks:
      - rocklov-network

  rocklov-web:
    image: qaninja/rocklov-web:v3
    container_name: rocklov-web
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - rocklov-network

networks:
  rocklov-network:
    name: rocklov-network
    driver: bridge
